### ISSUE TITLE
dREG.HD should import bigWig

### ISSUE THREAD

**Issue by omsai** [Danko-Lab/dREG.HD#1]
In a new packrat installation with R 3.4.1 I get the following error:

```
> library(dREG.HD)
 Error: package ‘bigWig’ required by ‘dREG.HD’ could not be found
```

Steps to reproduce:

1. Create a [packrat environment](https://rstudio.github.io/packrat/) in a new directory with `packrat::init()`
2. Restart R in the new directory to take advantage of the `.Rprofile` and local library created by packrat.
3. Install devtools to be able to install from GitHub: `install.packages("devtools")`
4. Install dREG.HD using devtools: `devtools::install_github("Danko-Lab/dREG.HD/dREG.HD")`  You will be prompted to install BiocInstaller for installing Bioconductor packages; say 1 for "Yes" at the prompt.
5. Install completes, but loading package fails when running `library(dREG.HD)`

**Comment by omsai** [comment]
It looks like the issue was needing to move dependencies from `Depends` to `Imports` per coregenomics/dREG.HD@66a5b57

```
> library(dREG.HD)
Warning message:
replacing previous import ‘stats::nobs’ by ‘rmutil::nobs’ when loading ‘dREG’ 
>
```

But the package currently has no unit tests to validate that the exported function dREG_HD would still work with the change.

**Comment by tinyi** [comment]
Hi Pariksheet,

Thanks for your feedback. Did you manage to run dREG.HD after installing
bigWig?

Best,

Tinyi

On Wed, Mar 28, 2018 at 12:02 PM, Pariksheet Nanda <notifications@github.com

**Comment by omsai** [comment]
No, I can't run `dREG.HD::dREG_HD` just yet after moving the packages from "Depends" to "Imports".  Not surprisingly, the code needs to be changed to explicitly use the package imports, and I'm adding a testthat test suite to try running `dREG_HD`.  I'm in class right now and will send a pull request after things are running.

**Comment by omsai** [comment]
dREG.HD installs with:

```R
devtools::install_github("coregenomics/dREG.HD/dREG.HD@issue-1-bigWig")
```

Added unit tests to run CPU mode with coregenomics@5dccd46.  But I still need to add another test for GPU mode:

```bash
Rscript -e 'devtools::test()'
```

```
Loading dREG.HD
Loading required package: testthat
Testing dREG.HD
✔ | OK F W S | Context
⠏ |  0       | dREG_HDR Version:  R version 3.4.1 (2017-06-30) 

Garbage collection 42 = 31+4+7 (level 2) ... 
38.8 Mbytes of cons cells used (62%)
92.6 Mbytes of vectors used (63%)
Garbage collection 43 = 31+4+8 (level 2) ... 
36.7 Mbytes of cons cells used (59%)
91.0 Mbytes of vectors used (62%)
Garbage collection 44 = 31+4+9 (level 2) ... 
36.7 Mbytes of cons cells used (59%)
91.0 Mbytes of vectors used (62%)
Garbage collection 45 = 31+4+10 (level 2) ... 
36.7 Mbytes of cons cells used (59%)
91.3 Mbytes of vectors used (62%)
Garbage collection 46 = 31+4+11 (level 2) ... 
37.9 Mbytes of cons cells used (61%)
91.8 Mbytes of vectors used (63%)
✔ |  1       | dREG_HD [233.4 s]

══ Results ═════════════════════════════════════════════════════════════════════
Duration: 233.5 s

OK:       1
Failed:   0
Warnings: 0
Skipped:  0
Warning message:
`encoding` is deprecated; all files now assumed to be UTF-8
```
